export { any } from './typer.js'
export type { $AnyAttributeState, $AnyAttributeNestedState } from './interface.js'
export { $AnyAttribute, AnyAttribute } from './interface.js'
export type { FreezeAnyAttribute } from './freeze.js'
export type { ResolveAnyAttribute } from './resolve.js'
