export type { BatchWriteItemRequest } from './BatchWriteItemRequest'
export type { BatchWriteOptions } from './options'
export { batchWrite } from './batchWrite'
export { BatchDeleteItemRequest } from './deleteItem'
export { BatchPutItemRequest } from './putItem'
