export { UpdateItemCommand } from './updateItemCommand.js'
export type { UpdateItemResponse } from './updateItemCommand.js'
export { $set, $get, $remove, $sum, $subtract, $add, $delete, $append, $prepend } from './utils.js'
export type { UpdateItemOptions } from './options.js'
export type { UpdateItemInput, AttributeUpdateItemInput } from './types.js'
export { parseUpdateExtension } from './updateItemParams/index.js'
