export { number } from './typer.js'
export type { $NumberAttributeState, $NumberAttributeNestedState } from './interface.js'
export { $NumberAttribute, NumberAttribute, NumberAttribute_ } from './interface.js'
export type { FreezeNumberAttribute } from './freeze.js'
export type { ResolveNumberAttribute, ResolvedNumberAttribute } from './resolve.js'
