export { number } from './typer.js'
export type { NumberSchema, $NumberAttributeNestedState } from './interface.js'
export { $NumberAttribute, NumberAttribute, NumberAttribute_ } from './interface.js'
export type { ResolveNumberSchema, ResolvedNumberSchema } from './resolve.js'
export type { NumberAttributeState } from './types.js'
