export { $add, isAddition, $ADD } from './add.js'
export type { ADD } from './add.js'
export { $append, isAppending, $APPEND } from './append.js'
export type { APPEND } from './append.js'
export { $delete, isDeletion, $DELETE } from './delete.js'
export type { DELETE } from './delete.js'
export { $get, isGetting, $GET } from './get.js'
export type { GET } from './get.js'
export { isExtension, $IS_EXTENSION } from './isExtension.js'
export type { Extension, Basic } from './isExtension.js'
export { $prepend, isPrepending, $PREPEND } from './prepend.js'
export type { PREPEND } from './prepend.js'
export { $remove, isRemoval, $REMOVE } from './remove.js'
export { $set, isSetting, $SET } from './set.js'
export type { SET } from './set.js'
export { $subtract, isSubtraction, $SUBTRACT } from './subtract.js'
export type { SUBTRACT } from './subtract.js'
export { $sum, isSum, $SUM } from './sum.js'
export type { SUM } from './sum.js'
