export { UpdateAttributesCommand } from './updateAttributesCommand.js'
export type { UpdateAttributesResponse } from './updateAttributesCommand.js'
export type { UpdateAttributesOptions } from './options.js'
export type { UpdateAttributesInput, UpdateAttributeInput } from './types.js'
export { parseUpdateAttributesExtension } from './updateAttributesParams/index.js'
